//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web062023.AMIS.Domain.Resources.FixedAsset {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FixedAsset {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FixedAsset() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web062023.AMIS.Domain.Resources.FixedAsset.FixedAsset", typeof(FixedAsset).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm thời chưa tạo mã được do có quá nhiều người. Thử lại sau 30 giây.
        /// </summary>
        public static string CanNotGenCode {
            get {
                return ResourceManager.GetString("CanNotGenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản {0} đã tồn tại.
        /// </summary>
        public static string FixedAssetCodeExist {
            get {
                return ResourceManager.GetString("FixedAssetCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại tài sản với id {0}.
        /// </summary>
        public static string FixedAssetIdNotExist {
            get {
                return ResourceManager.GetString("FixedAssetIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới {0} tài sản thành công.
        /// </summary>
        public static string InsertMany {
            get {
                return ResourceManager.GetString("InsertMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại tài sản nào thoả mãn.
        /// </summary>
        public static string NoAsset {
            get {
                return ResourceManager.GetString("NoAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang hiện tại phải lớn hơn 1.
        /// </summary>
        public static string PageNumberLessThanZero {
            get {
                return ResourceManager.GetString("PageNumberLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bản ghi 1 trang phải lớn hơn 1.
        /// </summary>
        public static string PageSizeLessThanZero {
            get {
                return ResourceManager.GetString("PageSizeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy vấn thất bại.
        /// </summary>
        public static string QueryFail {
            get {
                return ResourceManager.GetString("QueryFail", resourceCulture);
            }
        }
    }
}
